### ISSUE TITLE
Cannot require both slugify and python-slugify

### ISSUE THREAD

**Issue by FaustinCarter** [conda-forge/sphinx-material-feedstock#14]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

The deps for `python-slugify` were recently updated to ensure that it does not coexist with `slugify` as they are the same thing and can/will clobber each other. See discussion here: https://github.com/conda-forge/python-slugify-feedstock/issues/35

Is there a reason that both of these are pinned?

### Installed packages

```shell
n/a
```

### Environment info

```shell
n/a
```

**Comment by mwalsh161** [comment]
looks like https://github.com/conda-forge/sphinx-material-feedstock/pull/13 should satisfy this

**Comment by moorepants** [comment]
This should be fixed.
